version: '3.8'
services:
  db:
    image: postgres:14.4-alpine
    ports:
      - '5433:5433'
    networks:
      - igma-net
    restart: always
    volumes:
      - ./:/igma
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: igmadb
    command: -p 5433
  redis:
    image: redis:7.0.2-alpine
    networks:
      - igma-net
    restart: always
  api:
    image: igma-api
    build:
      dockerfile: ./src/Dockerfile
      context: .
      target: dev
    networks:
      - igma-net
    volumes:
      - .:/igma/app
      - /igma/app/node_modules
    ports:
      - '3001:3001'
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    command: yarn start:dev app
networks:
  igma-net:
    driver: bridge
